name: FallingCrate
author: tWizT3d_dreaMr
version: 0.2.2
main: me.tWizT3d_dreaMr.FallingCrate.main
commands:
   fallcrate:
      description: Makes a falling crate.
      usage: /fallcrate keyname <chest location>
   setfallcrate:
      description: Makes a falling crate.
      usage: setfallcrate x1 y1 z1 x2 y2 z2
   togglefallcrateevent:
      description: Makes a falling crate.
      usage: togglefallcrateevent
permissions:
  tCrate.create:
    default: op
    description: Allows the player to make a falling crate.
api-version: 1.13